### ISSUE TITLE
[CI] Notify Slack on star of repo workflow broken

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshkit#33]
**Description**
The slack.yml workflow (https://github.com/layer5io/meshkit/blob/master/.github/workflows/slack.yml) is broken. This workflow is invoked whenever a GitHub user stars the layer5io/meshkit repo. We have this same workflow included in all of the `layer5io` repos.

**Expected Behavior**
The community slack's #buzz channel should receive notification when this repo is starred.

The workflow linked above probably needs the repository name that it refers to updated.

**Comment by leecalcote** [comment]
@Vi1234sh12 would you like to pick this one up?

**Comment by leecalcote** [comment]
@Jagrati24 is this of interest? Would you like to be assigned this issue?

**Comment by leecalcote** [comment]
@piyushsingariya something that you might like to try?

**Comment by piyushsingariya** [comment]
Yeah sure, I'll try to look into it after the one I'm working on right now. :smiley:
