### ISSUE TITLE
[README] Update README Community Section

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/meshkit#53]
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
![img](https://user-images.githubusercontent.com/62384659/117368468-7cbfe400-aebb-11eb-92c2-0033fd74bcfc.png)
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

**Comment by Alenjojo** [comment]
I'll be happy to take up this issue

**Comment by leecalcote** [comment]
The following phrase should be used:

```
✔️ <em><strong>Access</strong></em> the <a href="https://drive.google.com/drive/u/4/folders/0ABH8aabN4WAKUk9PVA">Community Drive</a> by completing a community <a href="https://layer5.io/newcomer">Member Form</a>.<br />
```

**Comment by Alenjojo** [comment]
@leecalcote hey i assume this issue has been resolved already. And not only that there are other issue link the issue

**Comment by soham4abc** [comment]
This issue is resolved

**Comment by leecalcote** [comment]
Thank you, @soham4abc 👍
