### ISSUE TITLE
Define short, long descriptions, probably cause and suggested remediation for error codes

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshkit#9]
**Current Behavior**
The current error codes are missing this information.

**Desired Behavior**
Short, long descriptions, probably cause and suggested remediations should be defined for each  error code.

**Comment by leecalcote** [comment]
Progress - https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit#heading=h.3gmuxn6p14m9

**Comment by mgfeller** [comment]
@lee @kumarabd I think this has been implemented, and the issue can be closed. Agreed?

**Comment by mgfeller** [comment]
Most of the error codes contain now more details. Rather than keeping a general issue open (this one), I suggest more specific issues are created as the need arises.
